import type { FoodItem, Order } from './types'

// In-memory store for demo purposes
// In production, this would be replaced with a database

const foodItems: Map<string, FoodItem> = new Map([
  ['1', {
    id: '1',
    name: 'Butter Chicken',
    description: 'Tender chicken cooked in a creamy tomato-based sauce with butter, cream, and aromatic spices. Served with naan or basmati rice',
    price: 329,
    category: 'main',
    available: true,
    image: '/images/butter-chicken.jpg',
    rating: 4.8,
    prepTime: 20,
    calories: 420,
    spicyLevel: 2,
    isVegetarian: false,
    allergens: ['dairy'],
    createdAt: new Date().toISOString()
  }],
  ['2', {
    id: '2',
    name: 'Paneer Tikka Masala',
    description: 'Succulent cottage cheese cubes in a rich, creamy tomato sauce with bell peppers, onions, and traditional Indian spices',
    price: 299,
    category: 'main',
    available: true,
    image: '/images/paneer-tikka.jpg',
    rating: 4.9,
    prepTime: 18,
    calories: 380,
    spicyLevel: 2,
    isVegetarian: true,
    allergens: ['dairy'],
    createdAt: new Date().toISOString()
  }],
  ['3', {
    id: '3',
    name: 'Biryani - Hyderabadi',
    description: 'Fragrant basmati rice cooked with tender meat or vegetables, aromatic spices, and herbs in the traditional Hyderabadi style',
    price: 349,
    category: 'main',
    available: true,
    image: '/images/biryani.jpg',
    rating: 4.7,
    prepTime: 25,
    calories: 520,
    spicyLevel: 2,
    isVegetarian: false,
    allergens: [],
    createdAt: new Date().toISOString()
  }],
  ['4', {
    id: '4',
    name: 'Samosa - Potato & Peas',
    description: 'Crispy triangular pastry filled with spiced potatoes, green peas, and traditional Indian seasoning. Served with mint chutney',
    price: 79,
    category: 'appetizer',
    available: true,
    image: '/images/samosa.jpg',
    rating: 4.5,
    prepTime: 8,
    calories: 180,
    spicyLevel: 1,
    isVegetarian: true,
    allergens: ['gluten'],
    createdAt: new Date().toISOString()
  }],
  ['5', {
    id: '5',
    name: 'Tandoori Chicken',
    description: 'Succulent chicken marinated in yogurt and tandoori spices, charred in the traditional tandoor oven. Served with lemon and onions',
    price: 399,
    category: 'main',
    available: true,
    image: '/images/tandoori.jpg',
    rating: 4.9,
    prepTime: 22,
    calories: 380,
    spicyLevel: 2,
    isVegetarian: false,
    allergens: ['dairy'],
    createdAt: new Date().toISOString()
  }],
  ['6', {
    id: '6',
    name: 'Dosa - Crispy Rice & Lentil',
    description: 'Thin, crispy pancake made from fermented rice and lentil batter, filled with spiced potatoes and served with sambar and coconut chutney',
    price: 149,
    category: 'main',
    available: true,
    image: '/images/dosa.jpg',
    rating: 4.8,
    prepTime: 12,
    calories: 280,
    spicyLevel: 1,
    isVegetarian: true,
    allergens: ['gluten'],
    createdAt: new Date().toISOString()
  }],
  ['7', {
    id: '7',
    name: 'Chole Bhature',
    description: 'Spiced chickpeas curry paired with deep-fried fluffy wheat bread, topped with mint and served with pickled onions and chutney',
    price: 189,
    category: 'main',
    available: true,
    image: '/images/chole-bhature.jpg',
    rating: 4.6,
    prepTime: 15,
    calories: 450,
    spicyLevel: 3,
    isVegetarian: true,
    allergens: ['gluten'],
    createdAt: new Date().toISOString()
  }],
  ['8', {
    id: '8',
    name: 'Gulab Jamun',
    description: 'Soft, spongy milk solids dumplings soaked in sweet cardamom-infused sugar syrup. A classic Indian dessert served warm',
    price: 129,
    category: 'dessert',
    available: true,
    image: '/images/gulab-jamun.jpg',
    rating: 4.9,
    prepTime: 10,
    calories: 220,
    spicyLevel: 0,
    isVegetarian: true,
    allergens: ['dairy'],
    createdAt: new Date().toISOString()
  }],
  ['9', {
    id: '9',
    name: 'Palak Paneer',
    description: 'Cottage cheese cubes cooked in a smooth spinach curry with cream and spices. A nutritious and delicious vegetarian dish',
    price: 279,
    category: 'main',
    available: true,
    image: '/images/palak-paneer.jpg',
    rating: 4.7,
    prepTime: 18,
    calories: 350,
    spicyLevel: 1,
    isVegetarian: true,
    allergens: ['dairy'],
    createdAt: new Date().toISOString()
  }],
  ['10', {
    id: '10',
    name: 'Chicken Tikka Masala',
    description: 'Tender chunks of chicken marinated in yogurt and spices, cooked in a creamy tomato sauce with bell peppers',
    price: 319,
    category: 'main',
    available: true,
    image: '/images/chicken-tikka-masala.jpg',
    rating: 4.8,
    prepTime: 20,
    calories: 400,
    spicyLevel: 2,
    isVegetarian: false,
    allergens: ['dairy'],
    createdAt: new Date().toISOString()
  }],
  ['11', {
    id: '11',
    name: 'Aloo Gobi',
    description: 'Potatoes and cauliflower florets stir-fried with onions, tomatoes, and traditional Indian spices. A dry vegetable curry',
    price: 149,
    category: 'main',
    available: true,
    image: '/images/aloo-gobi.jpg',
    rating: 4.6,
    prepTime: 15,
    calories: 220,
    spicyLevel: 1,
    isVegetarian: true,
    allergens: [],
    createdAt: new Date().toISOString()
  }],
  ['12', {
    id: '12',
    name: 'Dal Makhani',
    description: 'Black lentils and kidney beans cooked overnight, finished with cream, butter, and aromatic spices. Rich and creamy',
    price: 199,
    category: 'main',
    available: true,
    image: '/images/dal-makhani.jpg',
    rating: 4.8,
    prepTime: 20,
    calories: 320,
    spicyLevel: 1,
    isVegetarian: true,
    allergens: ['dairy'],
    createdAt: new Date().toISOString()
  }],
  ['13', {
    id: '13',
    name: 'Onion Bhaji',
    description: 'Thinly sliced onions mixed with gram flour and spices, deep-fried until golden and crispy. Served with mint chutney',
    price: 99,
    category: 'appetizer',
    available: true,
    image: '/images/onion-bhaji.jpg',
    rating: 4.5,
    prepTime: 10,
    calories: 200,
    spicyLevel: 1,
    isVegetarian: true,
    allergens: ['gluten'],
    createdAt: new Date().toISOString()
  }],
  ['14', {
    id: '14',
    name: 'Spring Rolls - Vegetable',
    description: 'Crispy rolls filled with cabbage, carrots, and other fresh vegetables. Served with sweet and spicy dipping sauce',
    price: 129,
    category: 'appetizer',
    available: true,
    image: '/images/spring-rolls.jpg',
    rating: 4.6,
    prepTime: 10,
    calories: 250,
    spicyLevel: 0,
    isVegetarian: true,
    allergens: ['gluten'],
    createdAt: new Date().toISOString()
  }],
  ['15', {
    id: '15',
    name: 'Mango Lassi',
    description: 'Refreshing yogurt-based drink blended with fresh mango pulp, cardamom, and a touch of sweetness',
    price: 79,
    category: 'beverage',
    available: true,
    image: '/images/mango-lassi.jpg',
    rating: 4.7,
    prepTime: 5,
    calories: 150,
    spicyLevel: 0,
    isVegetarian: true,
    allergens: ['dairy'],
    createdAt: new Date().toISOString()
  }],
  ['16', {
    id: '16',
    name: 'Masala Chai',
    description: 'Traditional Indian spiced tea brewed with cardamom, cloves, cinnamon, and ginger. Served with milk and sugar',
    price: 49,
    category: 'beverage',
    available: true,
    image: '/images/masala-chai.jpg',
    rating: 4.8,
    prepTime: 5,
    calories: 80,
    spicyLevel: 1,
    isVegetarian: true,
    allergens: ['dairy'],
    createdAt: new Date().toISOString()
  }],
  ['17', {
    id: '17',
    name: 'Rogan Josh',
    description: 'Tender lamb pieces cooked in a fragrant tomato-based curry with yogurt, aromatic spices, and slow cooking',
    price: 399,
    category: 'main',
    available: true,
    image: '/images/rogan-josh.jpg',
    rating: 4.8,
    prepTime: 25,
    calories: 420,
    spicyLevel: 2,
    isVegetarian: false,
    allergens: ['dairy'],
    createdAt: new Date().toISOString()
  }],
  ['18', {
    id: '18',
    name: 'Idli - Rice Cake',
    description: 'Soft and fluffy steamed rice cakes made from fermented rice and lentil batter. Served with sambar and chutney',
    price: 99,
    category: 'main',
    available: true,
    image: '/images/idli.jpg',
    rating: 4.7,
    prepTime: 10,
    calories: 150,
    spicyLevel: 0,
    isVegetarian: true,
    allergens: ['gluten'],
    createdAt: new Date().toISOString()
  }],
  ['19', {
    id: '19',
    name: 'Vada - Lentil Fritter',
    description: 'Golden, crispy fried lentil fritters with a fluffy interior. Served with sambar and coconut chutney',
    price: 89,
    category: 'appetizer',
    available: true,
    image: '/images/vada.jpg',
    rating: 4.6,
    prepTime: 10,
    calories: 180,
    spicyLevel: 1,
    isVegetarian: true,
    allergens: ['gluten'],
    createdAt: new Date().toISOString()
  }],
  ['20', {
    id: '20',
    name: 'Fish Curry - Coastal Style',
    description: 'Fresh fish cooked in a coconut-based curry with aromatic spices, curry leaves, and a hint of tamarind',
    price: 349,
    category: 'main',
    available: true,
    image: '/images/fish-curry.jpg',
    rating: 4.7,
    prepTime: 20,
    calories: 320,
    spicyLevel: 2,
    isVegetarian: false,
    allergens: ['fish', 'coconut'],
    createdAt: new Date().toISOString()
  }],
  ['21', {
    id: '21',
    name: 'Kheer - Rice Pudding',
    description: 'Creamy rice pudding made with basmati rice, condensed milk, and aromatic spices. Topped with dried fruits and nuts',
    price: 109,
    category: 'dessert',
    available: true,
    image: '/images/kheer.jpg',
    rating: 4.8,
    prepTime: 15,
    calories: 280,
    spicyLevel: 0,
    isVegetarian: true,
    allergens: ['dairy', 'nuts'],
    createdAt: new Date().toISOString()
  }],
  ['22', {
    id: '22',
    name: 'Rasgulla - Cheese Balls',
    description: 'Spongy cottage cheese balls dipped in light sugar syrup. A classic Bengali sweet dessert served chilled',
    price: 119,
    category: 'dessert',
    available: true,
    image: '/images/rasgulla.jpg',
    rating: 4.8,
    prepTime: 10,
    calories: 200,
    spicyLevel: 0,
    isVegetarian: true,
    allergens: ['dairy'],
    createdAt: new Date().toISOString()
  }],
  ['23', {
    id: '23',
    name: 'Naan - Garlic & Butter',
    description: 'Soft, fluffy Indian bread baked in a traditional tandoor oven, topped with garlic, butter, and herbs',
    price: 59,
    category: 'bread',
    available: true,
    image: '/images/garlic-naan.jpg',
    rating: 4.9,
    prepTime: 8,
    calories: 220,
    spicyLevel: 0,
    isVegetarian: true,
    allergens: ['dairy', 'gluten'],
    createdAt: new Date().toISOString()
  }],
  ['24', {
    id: '24',
    name: 'Roti - Whole Wheat',
    description: 'Traditional whole wheat flatbread cooked on a griddle with a light touch of ghee. Simple and nutritious',
    price: 29,
    category: 'bread',
    available: true,
    image: '/images/roti.jpg',
    rating: 4.8,
    prepTime: 5,
    calories: 100,
    spicyLevel: 0,
    isVegetarian: true,
    allergens: ['gluten'],
    createdAt: new Date().toISOString()
  }],
  ['25', {
    id: '25',
    name: 'Jalebi - Orange Swirl',
    description: 'Bright orange, sweet crispy spiral pastries made with flour and soaked in sugar syrup. Traditional festive sweet',
    price: 89,
    category: 'dessert',
    available: true,
    image: '/images/jalebi.jpg',
    rating: 4.6,
    prepTime: 12,
    calories: 250,
    spicyLevel: 0,
    isVegetarian: true,
    allergens: ['gluten'],
    createdAt: new Date().toISOString()
  }],
  ['26', {
    id: '26',
    name: 'Vegetable Biryani',
    description: 'Aromatic basmati rice layered with mixed vegetables, herbs, and spices. A fragrant vegetarian rice dish',
    price: 229,
    category: 'main',
    available: true,
    image: '/images/veg-biryani.jpg',
    rating: 4.7,
    prepTime: 22,
    calories: 450,
    spicyLevel: 1,
    isVegetarian: true,
    allergens: [],
    createdAt: new Date().toISOString()
  }],
  ['27', {
    id: '27',
    name: 'Shrimp Biryani',
    description: 'Fragrant basmati rice cooked with succulent shrimp, herbs, and aromatic spices in the traditional style',
    price: 379,
    category: 'main',
    available: true,
    image: '/images/shrimp-biryani.jpg',
    rating: 4.8,
    prepTime: 24,
    calories: 480,
    spicyLevel: 2,
    isVegetarian: false,
    allergens: ['shellfish'],
    createdAt: new Date().toISOString()
  }],
  ['28', {
    id: '28',
    name: 'Paneer Naan',
    description: 'Soft naan bread stuffed with spiced cottage cheese and herbs, baked in a tandoor oven',
    price: 119,
    category: 'bread',
    available: true,
    image: '/images/paneer-naan.jpg',
    rating: 4.8,
    prepTime: 10,
    calories: 280,
    spicyLevel: 1,
    isVegetarian: true,
    allergens: ['dairy', 'gluten'],
    createdAt: new Date().toISOString()
  }],
  ['29', {
    id: '29',
    name: 'Chicken Biryani',
    description: 'Aromatic basmati rice layered with tender chicken pieces, herbs, and traditional biryani spices. Slow-cooked to perfection',
    price: 349,
    category: 'main',
    available: true,
    image: '/images/chicken-biryani.jpg',
    rating: 4.9,
    prepTime: 24,
    calories: 500,
    spicyLevel: 2,
    isVegetarian: false,
    allergens: [],
    createdAt: new Date().toISOString()
  }],
  ['30', {
    id: '30',
    name: 'Shahi Tukda - Royal Dessert',
    description: 'Layers of crispy bread, dry fruits, and cream soaked in cardamom-infused milk. A royal Mughlai dessert',
    price: 159,
    category: 'dessert',
    available: true,
    image: '/images/shahi-tukda.jpg',
    rating: 4.9,
    prepTime: 12,
    calories: 420,
    spicyLevel: 0,
    isVegetarian: true,
    allergens: ['dairy', 'gluten', 'nuts'],
    createdAt: new Date().toISOString()
  }],
  ['31', {
    id: '31',
    name: 'Ramen - Spicy Broth',
    description: 'Japanese noodles in a rich, spicy broth with tender chicken, vegetables, and aromatic spices. Topped with green onions and sesame seeds',
    price: 279,
    category: 'main',
    available: true,
    image: '/images/ramen.jpg',
    rating: 4.7,
    prepTime: 15,
    calories: 380,
    spicyLevel: 3,
    isVegetarian: false,
    allergens: ['gluten', 'soy'],
    createdAt: new Date().toISOString()
  }],
  ['32', {
    id: '32',
    name: 'Laccha Paratha',
    description: 'Flaky, layered Indian flatbread with crispy edges and soft interior, cooked with butter. Served with yogurt and pickle',
    price: 79,
    category: 'bread',
    available: true,
    image: '/images/laccha-paratha.jpg',
    rating: 4.8,
    prepTime: 12,
    calories: 280,
    spicyLevel: 0,
    isVegetarian: true,
    allergens: ['dairy', 'gluten'],
    createdAt: new Date().toISOString()
  }],
  ['33', {
    id: '33',
    name: 'Momos - Vegetable',
    description: 'Steamed dumplings filled with fresh vegetables, ginger, and garlic. Served with spicy red chutney for dipping',
    price: 129,
    category: 'appetizer',
    available: true,
    image: '/images/momos-veg.jpg',
    rating: 4.6,
    prepTime: 12,
    calories: 180,
    spicyLevel: 1,
    isVegetarian: true,
    allergens: ['gluten'],
    createdAt: new Date().toISOString()
  }],
  ['34', {
    id: '34',
    name: 'Momos - Chicken',
    description: 'Steamed dumplings filled with minced chicken, ginger, and aromatic spices. Served with spicy red chutney and soy sauce',
    price: 159,
    category: 'appetizer',
    available: true,
    image: '/images/momos-chicken.jpg',
    rating: 4.7,
    prepTime: 12,
    calories: 200,
    spicyLevel: 2,
    isVegetarian: false,
    allergens: ['gluten', 'soy'],
    createdAt: new Date().toISOString()
  }],
  ['35', {
    id: '35',
    name: 'Momos - Mutton',
    description: 'Steamed dumplings filled with minced mutton, ginger, garlic, and traditional spices. Served with fiery red chutney',
    price: 189,
    category: 'appetizer',
    available: true,
    image: '/images/momos-mutton.jpg',
    rating: 4.7,
    prepTime: 12,
    calories: 220,
    spicyLevel: 3,
    isVegetarian: false,
    allergens: ['gluten'],
    createdAt: new Date().toISOString()
  }],
  ['36', {
    id: '36',
    name: 'Diet Coke',
    description: 'Refreshing Coca-Cola Diet soft drink. Chilled and served in a glass with ice',
    price: 49,
    category: 'beverage',
    available: true,
    image: '/images/diet-coke.jpg',
    rating: 4.5,
    prepTime: 2,
    calories: 0,
    spicyLevel: 0,
    isVegetarian: true,
    allergens: [],
    createdAt: new Date().toISOString()
  }],
  ['37', {
    id: '37',
    name: 'Pepsi',
    description: 'Classic Pepsi cola soft drink. Ice-cold and refreshing with a crisp, citrusy taste',
    price: 49,
    category: 'beverage',
    available: true,
    image: '/images/pepsi.jpg',
    rating: 4.4,
    prepTime: 2,
    calories: 150,
    spicyLevel: 0,
    isVegetarian: true,
    allergens: [],
    createdAt: new Date().toISOString()
  }],
  ['38', {
    id: '38',
    name: 'Sprite',
    description: 'Crisp and refreshing lemon-lime flavored soft drink. Served ice-cold',
    price: 49,
    category: 'beverage',
    available: true,
    image: '/images/sprite.jpg',
    rating: 4.5,
    prepTime: 2,
    calories: 140,
    spicyLevel: 0,
    isVegetarian: true,
    allergens: [],
    createdAt: new Date().toISOString()
  }],
  ['39', {
    id: '39',
    name: 'Fanta - Orange',
    description: 'Vibrant and fruity orange flavored soft drink. Served ice-cold and refreshing',
    price: 49,
    category: 'beverage',
    available: true,
    image: '/images/fanta-orange.jpg',
    rating: 4.4,
    prepTime: 2,
    calories: 160,
    spicyLevel: 0,
    isVegetarian: true,
    allergens: [],
    createdAt: new Date().toISOString()
  }],
  ['40', {
    id: '40',
    name: 'Mountain Dew',
    description: 'Bold and exhilarating citrus soft drink with an exciting taste. Served chilled',
    price: 49,
    category: 'beverage',
    available: true,
    image: '/images/mountain-dew.jpg',
    rating: 4.3,
    prepTime: 2,
    calories: 170,
    spicyLevel: 0,
    isVegetarian: true,
    allergens: [],
    createdAt: new Date().toISOString()
  }],
  ['41', {
    id: '41',
    name: 'Raita - Yogurt Sides',
    description: 'Cool yogurt side dish with cucumber, tomatoes, and aromatic spices. Perfect complement to spicy curries',
    price: 59,
    category: 'sides',
    available: true,
    image: '/images/raita.jpg',
    rating: 4.7,
    prepTime: 5,
    calories: 100,
    spicyLevel: 0,
    isVegetarian: true,
    allergens: ['dairy'],
    createdAt: new Date().toISOString()
  }],
  ['42', {
    id: '42',
    name: 'Green Salad',
    description: 'Fresh mixed greens with cucumber, tomatoes, bell peppers, and onions. Dressed with lemon vinaigrette and herbs',
    price: 79,
    category: 'sides',
    available: true,
    image: '/images/green-salad.jpg',
    rating: 4.6,
    prepTime: 5,
    calories: 80,
    spicyLevel: 0,
    isVegetarian: true,
    allergens: [],
    createdAt: new Date().toISOString()
  }],
  ['43', {
    id: '43',
    name: 'Tandoori Lamb Chops',
    description: 'Succulent lamb chops marinated in yogurt and spices, cooked in a tandoor oven until charred and tender',
    price: 449,
    category: 'main',
    available: true,
    image: '/images/tandoori-lamb-chops.jpg',
    rating: 4.9,
    prepTime: 20,
    calories: 480,
    spicyLevel: 2,
    isVegetarian: false,
    allergens: ['dairy'],
    createdAt: new Date().toISOString()
  }],
  ['44', {
    id: '44',
    name: 'Mutton Keema',
    description: 'Minced mutton cooked with onions, ginger-garlic, and aromatic spices. A flavorful non-vegetarian curry',
    price: 319,
    category: 'main',
    available: true,
    image: '/images/mutton-keema.jpg',
    rating: 4.7,
    prepTime: 18,
    calories: 380,
    spicyLevel: 2,
    isVegetarian: false,
    allergens: [],
    createdAt: new Date().toISOString()
  }],
  ['45', {
    id: '45',
    name: 'Prawn Masala',
    description: 'Succulent prawns cooked in a spicy tomato-based curry with bell peppers and aromatic Indian spices',
    price: 399,
    category: 'main',
    available: true,
    image: '/images/prawn-masala.jpg',
    rating: 4.8,
    prepTime: 18,
    calories: 320,
    spicyLevel: 2,
    isVegetarian: false,
    allergens: ['shellfish'],
    createdAt: new Date().toISOString()
  }],
  ['46', {
    id: '46',
    name: 'Chicken Chettinad',
    description: 'Spicy South Indian chicken curry with roasted spices, coconut, and traditional Chettinad flavors. Medium to hot',
    price: 289,
    category: 'main',
    available: true,
    image: '/images/chicken-chettinad.jpg',
    rating: 4.8,
    prepTime: 20,
    calories: 350,
    spicyLevel: 3,
    isVegetarian: false,
    allergens: ['coconut'],
    createdAt: new Date().toISOString()
  }],
  ['47', {
    id: '47',
    name: 'Kurkure Mushroom',
    description: 'Crispy deep-fried button mushrooms coated in seasoned batter. Served with mint chutney and lemon wedges',
    price: 139,
    category: 'appetizer',
    available: true,
    image: '/images/kurkure-mushroom.jpg',
    rating: 4.8,
    prepTime: 10,
    calories: 220,
    spicyLevel: 1,
    isVegetarian: true,
    allergens: ['gluten'],
    createdAt: new Date().toISOString()
  }],
  ['48', {
    id: '48',
    name: 'Lamb Nihari',
    description: 'Slow-cooked lamb curry with thick, rich gravy infused with aromatic spices and traditional nihari masala',
    price: 379,
    category: 'main',
    available: true,
    image: '/images/lamb-nihari.jpg',
    rating: 4.8,
    prepTime: 25,
    calories: 420,
    spicyLevel: 2,
    isVegetarian: false,
    allergens: [],
    createdAt: new Date().toISOString()
  }],
  ['49', {
    id: '49',
    name: 'Crab Masala',
    description: 'Fresh crab pieces cooked in a savory masala curry with coconut, peppers, and traditional coastal spices',
    price: 499,
    category: 'main',
    available: true,
    image: '/images/crab-masala.jpg',
    rating: 4.9,
    prepTime: 22,
    calories: 280,
    spicyLevel: 2,
    isVegetarian: false,
    allergens: ['shellfish', 'coconut'],
    createdAt: new Date().toISOString()
  }],
  ['50', {
    id: '50',
    name: 'Chicken Lollipop',
    description: 'Tender chicken drumettes marinated and deep-fried until crispy. Served with spicy sauce and lemon',
    price: 249,
    category: 'appetizer',
    available: true,
    image: '/images/chicken-lollipop.jpg',
    rating: 4.7,
    prepTime: 12,
    calories: 350,
    spicyLevel: 2,
    isVegetarian: false,
    allergens: ['gluten'],
    createdAt: new Date().toISOString()
  }],
  ['51', {
    id: '51',
    name: 'Rumali Roti',
    description: 'Ultra-thin and delicate Indian flatbread cooked on a dome griddle, rolled and served hot with butter',
    price: 49,
    category: 'bread',
    available: true,
    image: '/images/rumali-roti.jpg',
    rating: 4.8,
    prepTime: 6,
    calories: 120,
    spicyLevel: 0,
    isVegetarian: true,
    allergens: ['gluten'],
    createdAt: new Date().toISOString()
  }],
  ['52', {
    id: '52',
    name: 'Kathi Roll',
    description: 'Crispy paratha wrapped with spiced chicken, eggs, onions, and peppers. Served with mint and garlic chutney',
    price: 149,
    category: 'main',
    available: true,
    image: '/images/kathi-roll.jpg',
    rating: 4.7,
    prepTime: 10,
    calories: 380,
    spicyLevel: 2,
    isVegetarian: false,
    allergens: ['gluten', 'dairy'],
    createdAt: new Date().toISOString()
  }],
  ['53', {
    id: '53',
    name: 'Golgappe - Pani Puri',
    description: 'Crispy hollow puris filled with spiced potatoes, chickpeas, and tangy tamarind water. A classic Indian street snack',
    price: 89,
    category: 'chaat',
    available: true,
    image: '/images/golgappe.jpg',
    rating: 4.6,
    prepTime: 8,
    calories: 150,
    spicyLevel: 2,
    isVegetarian: true,
    allergens: ['gluten'],
    createdAt: new Date().toISOString()
  }],
  ['54', {
    id: '54',
    name: 'Aloo Tikki',
    description: 'Golden fried potato and pea patties served with tamarind and mint chutney. A delicious street food favorite',
    price: 79,
    category: 'chaat',
    available: true,
    image: '/images/aloo-tikki.jpg',
    rating: 4.7,
    prepTime: 8,
    calories: 180,
    spicyLevel: 1,
    isVegetarian: true,
    allergens: ['gluten'],
    createdAt: new Date().toISOString()
  }],
  ['55', {
    id: '55',
    name: 'Dahi Bhalla',
    description: 'Soft, fluffy lentil dumplings soaked in creamy yogurt and topped with sweet and spicy chutneys. A refreshing chaat',
    price: 99,
    category: 'chaat',
    available: true,
    image: '/images/dahi-bhalla.jpg',
    rating: 4.8,
    prepTime: 10,
    calories: 160,
    spicyLevel: 1,
    isVegetarian: true,
    allergens: ['dairy', 'gluten'],
    createdAt: new Date().toISOString()
  }],
  ['56', {
    id: '56',
    name: 'Palak Chaat',
    description: 'Crispy spinach fritters with yogurt, tamarind chutney, and aromatic spice powder. A healthy and tasty chaat item',
    price: 109,
    category: 'chaat',
    available: true,
    image: '/images/palak-chaat.jpg',
    rating: 4.7,
    prepTime: 10,
    calories: 140,
    spicyLevel: 1,
    isVegetarian: true,
    allergens: ['gluten'],
    createdAt: new Date().toISOString()
  }],
  ['57', {
    id: '57',
    name: 'Margherita Pizza',
    description: 'Classic pizza with fresh mozzarella, tomato sauce, basil, and olive oil on a crispy crust',
    price: 249,
    category: 'main',
    available: true,
    image: '/images/margherita-pizza.jpg',
    rating: 4.7,
    prepTime: 12,
    calories: 450,
    spicyLevel: 0,
    isVegetarian: true,
    allergens: ['dairy', 'gluten'],
    createdAt: new Date().toISOString()
  }],
  ['58', {
    id: '58',
    name: 'Pepperoni Pizza',
    description: 'Classic pizza topped with pepperoni, cheese, and tomato sauce on a crispy crust',
    price: 279,
    category: 'main',
    available: true,
    image: '/images/pepperoni-pizza.jpg',
    rating: 4.6,
    prepTime: 12,
    calories: 500,
    spicyLevel: 1,
    isVegetarian: false,
    allergens: ['dairy', 'gluten'],
    createdAt: new Date().toISOString()
  }],
  ['59', {
    id: '59',
    name: 'Veggie Pizza',
    description: 'Loaded pizza with bell peppers, onions, mushrooms, olives, and fresh vegetables on a crispy crust',
    price: 259,
    category: 'main',
    available: true,
    image: '/images/veggie-pizza.jpg',
    rating: 4.6,
    prepTime: 12,
    calories: 420,
    spicyLevel: 0,
    isVegetarian: true,
    allergens: ['dairy', 'gluten'],
    createdAt: new Date().toISOString()
  }],
  ['60', {
    id: '60',
    name: 'Pasta Carbonara',
    description: 'Creamy Italian pasta with bacon, eggs, and parmesan cheese. A classic Roman pasta dish',
    price: 249,
    category: 'main',
    available: true,
    image: '/images/pasta-carbonara.jpg',
    rating: 4.7,
    prepTime: 12,
    calories: 480,
    spicyLevel: 0,
    isVegetarian: false,
    allergens: ['dairy', 'gluten'],
    createdAt: new Date().toISOString()
  }],
  ['61', {
    id: '61',
    name: 'Pasta Alfredo',
    description: 'Creamy pasta with rich parmesan sauce, butter, and fresh parsley. A classic Italian favorite',
    price: 239,
    category: 'main',
    available: true,
    image: '/images/pasta-alfredo.jpg',
    rating: 4.7,
    prepTime: 10,
    calories: 450,
    spicyLevel: 0,
    isVegetarian: true,
    allergens: ['dairy', 'gluten'],
    createdAt: new Date().toISOString()
  }],
  ['62', {
    id: '62',
    name: 'Spaghetti Bolognese',
    description: 'Italian spaghetti with rich meat sauce made from ground beef, tomatoes, and aromatic spices',
    price: 269,
    category: 'main',
    available: true,
    image: '/images/spaghetti-bolognese.jpg',
    rating: 4.7,
    prepTime: 14,
    calories: 520,
    spicyLevel: 0,
    isVegetarian: false,
    allergens: ['gluten'],
    createdAt: new Date().toISOString()
  }],
  ['63', {
    id: '63',
    name: 'Gajar Ka Halwa',
    description: 'Sweet carrot pudding made with grated carrots, ghee, milk, and topped with dry fruits and nuts',
    price: 129,
    category: 'dessert',
    available: true,
    image: '/images/gajar-ka-halwa.jpg',
    rating: 4.8,
    prepTime: 20,
    calories: 380,
    spicyLevel: 0,
    isVegetarian: true,
    allergens: ['dairy', 'nuts'],
    createdAt: new Date().toISOString()
  }],
  ['64', {
    id: '64',
    name: 'Rasmalai',
    description: 'Soft cottage cheese dumplings in a creamy sweet milk infused with cardamom and topped with pistachios',
    price: 139,
    category: 'dessert',
    available: true,
    image: '/images/rasmalai.jpg',
    rating: 4.9,
    prepTime: 10,
    calories: 280,
    spicyLevel: 0,
    isVegetarian: true,
    allergens: ['dairy', 'nuts'],
    createdAt: new Date().toISOString()
  }],
  ['65', {
    id: '65',
    name: 'Kulfi - Pistachio',
    description: 'Traditional frozen Indian dessert made with condensed milk and topped with crushed pistachios',
    price: 69,
    category: 'dessert',
    available: true,
    image: '/images/kulfi.jpg',
    rating: 4.8,
    prepTime: 5,
    calories: 200,
    spicyLevel: 0,
    isVegetarian: true,
    allergens: ['dairy', 'nuts'],
    createdAt: new Date().toISOString()
  }],
  ['66', {
    id: '66',
    name: 'Falooda',
    description: 'Refreshing dessert drink with vermicelli, ice cream, and sweet rose syrup. A perfect summer treat',
    price: 99,
    category: 'dessert',
    available: true,
    image: '/images/falooda.jpg',
    rating: 4.7,
    prepTime: 8,
    calories: 250,
    spicyLevel: 0,
    isVegetarian: true,
    allergens: ['dairy'],
    createdAt: new Date().toISOString()
  }]
])

const orders: Map<string, Order> = new Map()

export const store = {
  // Food Items
  getAllFoodItems: (): FoodItem[] => Array.from(foodItems.values()),
  
  getFoodItem: (id: string): FoodItem | undefined => foodItems.get(id),
  
  addFoodItem: (item: Omit<FoodItem, 'id' | 'createdAt'>): FoodItem => {
    const id = Date.now().toString()
    const newItem: FoodItem = {
      ...item,
      id,
      createdAt: new Date().toISOString()
    }
    foodItems.set(id, newItem)
    return newItem
  },
  
  updateFoodItem: (id: string, updates: Partial<Omit<FoodItem, 'id' | 'createdAt'>>): FoodItem | null => {
    const existing = foodItems.get(id)
    if (!existing) return null
    const updated = { ...existing, ...updates }
    foodItems.set(id, updated)
    return updated
  },
  
  deleteFoodItem: (id: string): boolean => {
    return foodItems.delete(id)
  },

  // Orders
  getAllOrders: (): Order[] => Array.from(orders.values()).sort((a, b) => 
    new Date(b.createdAt).getTime() - new Date(a.createdAt).getTime()
  ),
  
  getOrder: (id: string): Order | undefined => orders.get(id),
  
  createOrder: (order: Omit<Order, 'id' | 'createdAt' | 'status' | 'estimatedDelivery'>): Order => {
    const id = Date.now().toString()
    const estimatedMinutes = 30 + Math.floor(Math.random() * 15)
    const estimatedDelivery = new Date(Date.now() + estimatedMinutes * 60000).toISOString()
    const newOrder: Order = {
      ...order,
      id,
      status: 'pending',
      estimatedDelivery,
      createdAt: new Date().toISOString()
    }
    orders.set(id, newOrder)
    return newOrder
  },
  
  updateOrderStatus: (id: string, status: Order['status']): Order | null => {
    const existing = orders.get(id)
    if (!existing) return null
    const updated = { ...existing, status }
    orders.set(id, updated)
    return updated
  },
  
  deleteOrder: (id: string): boolean => {
    return orders.delete(id)
  },

  // Stats
  getStats: () => {
    const allOrders = Array.from(orders.values())
    const totalRevenue = allOrders
      .filter(o => o.status !== 'cancelled')
      .reduce((sum, o) => sum + o.totalAmount, 0)
    const pendingOrders = allOrders.filter(o => o.status === 'pending').length
    const completedOrders = allOrders.filter(o => o.status === 'delivered').length
    
    return {
      totalItems: foodItems.size,
      totalOrders: allOrders.length,
      totalRevenue,
      pendingOrders,
      completedOrders
    }
  }
}
